[package]
name = "into_val_derive"
version = "0.1.0"
authors = ["David Kyle <david.kyle@gmail.com>"]
license = "MIT"
description = "custom derive for rush shell"

[lib]
proc-macro = true

[dependencies]
syn = "0.10.5"
quote = "0.3.10"
