[package]
name = "rush_parser"
version = "0.1.0"
authors = ["David Kyle <david.kyle@gmail.com>"]

[dependencies]
regex = "0.2"
lazy_static = "0.2.2"
odds = "*"

[dependencies.rush_pat]
path = "../rush_pat"
version = "*"

[dependencies.plex]
path = "../../plex"
version = "*"
